openapi: 3.0.0
info:
  title: Social Media API
  description: API documentation for the social media application
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john.doe@example.com
                password:
                  type: string
                  example: password123
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
        500:
          description: Internal server error
  /auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: john.doe@example.com
                password:
                  type: string
                  example: password123
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: your.jwt.token
        401:
          description: Invalid email or password
        500:
          description: Internal server error

  /feed:
    get:
      summary: Get the user's feed
      security:
        - bearerAuth: []
      responses:
        200:
          description: Feed retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    created_by:
                      type: integer
                    type:
                      type: string
                    media_url:
                      type: string
                    media_text:
                      type: string
                    total_likes:
                      type: integer
                    comments_enabled:
                      type: boolean
                    comments:
                      type: array
                      items:
                        type: object
                        properties:
                          comment:
                            type: string
                          user:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              email:
                                type: string
        500:
          description: Internal server error

  /posts:
    post:
      summary: Create a new post
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - mediaUrl
                - mediaText
                - commentsEnabled
              properties:
                type:
                  type: string
                  example: image
                mediaUrl:
                  type: string
                  example: http://example.com/image.jpg
                mediaText:
                  type: string
                  example: Check out this image!
                commentsEnabled:
                  type: boolean
                  example: true
      responses:
        201:
          description: Post created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
        500:
          description: Internal server error

  /posts/{postId}/like:
    post:
      summary: Like or unlike a post
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Post liked/unliked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  isLiked:
                    type: boolean
        500:
          description: Internal server error

  /posts/{postId}/comments:
    post:
      summary: Comment on a post
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - comment
              properties:
                comment:
                  type: string
                  example: Nice post!
      responses:
        201:
          description: Comment added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Comment added successfully
        500:
          description: Internal server error

  /posts/{postId}:
    get:
      summary: Get a post
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Post retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: integer
                  post_text:
                    type: string
                  post_asset:
                    type: string
                  post_type:
                    type: string
                  likes:
                    type: integer
                  like_user_id:
                    type: integer
                  comment_id:
                    type: integer
                  comment_user_id:
                    type: integer
                  comment_content:
                    type: string
        404:
          description: Post not found
        500:
          description: Internal server error

  /users/follow:
    post:
      summary: Follow a user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - follower_id
              properties:
                follower_id:
                  type: integer
                  example: 2
      responses:
        201:
          description: User followed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User followed successfully
        500:
          description: Internal server error

  /users/profile:
    get:
      summary: Get the user's profile
      security:
        - bearerAuth: []
      responses:
        200:
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
        500:
          description: Internal server error

  /users/query-user:
    get:
      summary: Query a user
      security:
        - bearerAuth: []
      parameters:
        - name: field
          in: query
          required: true
          schema:
            type: string
            enum: [id, name, email]
            example: email
        - name: value
          in: query
          required: true
          schema:
            type: string
            example: john.doe@example.com
      responses:
        200:
          description: User queried successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        email:
                          type: string
                        name:
                          type: string
        400:
          description: Bad data
        500:
          description: Internal server error

  /users/followers:
    get:
      summary: Get user's followers
      security:
        - bearerAuth: []
      responses:
        200:
          description: Followers retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
        500:
          description: Internal server error

  /users/following:
    get:
      summary: Get users followed by the user
      security:
        - bearerAuth: []
      responses:
        200:
          description: Following users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
        500:
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
